/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CompaniesCompanyIdTransactionsRouteImport } from './routes/companies/$companyId/transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesCompanyIdTransactionsRoute =
  CompaniesCompanyIdTransactionsRouteImport.update({
    id: '/companies/$companyId/transactions',
    path: '/companies/$companyId/transactions',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/companies/$companyId/transactions': typeof CompaniesCompanyIdTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies/$companyId/transactions': typeof CompaniesCompanyIdTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/companies/$companyId/transactions': typeof CompaniesCompanyIdTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/companies/$companyId/transactions'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/companies/$companyId/transactions'
  id: '__root__' | '/' | '/companies/$companyId/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CompaniesCompanyIdTransactionsRoute: typeof CompaniesCompanyIdTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/$companyId/transactions': {
      id: '/companies/$companyId/transactions'
      path: '/companies/$companyId/transactions'
      fullPath: '/companies/$companyId/transactions'
      preLoaderRoute: typeof CompaniesCompanyIdTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CompaniesCompanyIdTransactionsRoute: CompaniesCompanyIdTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
